name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1 
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '8.0'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        run: ./gradlew build
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: ls 
      - name: Build the Docker image
        run: docker build -f sdf -t ghcr.io/anjanmadaram/prom/new:1 .
        
      - name: Docker login
        run: docker login ghcr.io --username ${{ secrets.DOCKER_USER_NAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
        
      - name: Docker push
        run: docker push ghcr.io/anjanmadaram/prom/new:1
        
    
