name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1    
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      
      - name: Build the Docker image
        run: docker build -f sdf -t ghcr.io/anjanmadaram/prom/new:1 .
        
      - name: Docker login
        run: docker login ghcr.io --username ${{ secrets.DOCKER_USER_NAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
        
      - name: Docker push
        run: docker push ghcr.io/anjanmadaram/prom/new:1
        
    
